# set to true if you want configure the game by config.yml
# <!> warn <!> dont forget to run /skydefender reloadconfig

rules:
  # alone -> only defender, attacker and spectator teams
  # teams -> enable all teams (9 without spectator team)
  game-type: alone

  # true -> example "one attacker just die"
  # false -> example "attacker killed by {player_name}"
  hide-death: true

  # true -> example "one defender just die"
  # false -> example "your team mate die by {die_reason}"
  hide-death-for-teams: false

  pvp-at-day: 3 # set to 0 for disable

  # enable or disable dimensions type
  world:
    nether:
      enable: true
      at-day: 5 # set to 0 for
      # true -> defender can use nether before attacker
      bypass-defender: true
    end:
      enable: false
      at-day: 0 # set to 0 for
      bypass-defender: false # true -> defender can use nether before attacker

  teams:
    # random  -> generated randomly
    # manual -> operator setup team
    # choose -> player choose team
    mode: manual # random / manual / choose

    # true -> team can fight in self
    friendly-fire: false

    # if game-type is alone this feature explain a private
    # chat for all attacker and private chat for defender
    # run /all for speaks to all
    private-chat-for-team: true

    # only if mode : random
    max-attacker-teams: 6
    max-player-per-teams: 4
